#!/bin/bash
echo "[testing queue module]"
./runtest.sh "tqueue 1" "open a queue then close it"
./runtest.sh "tqueue 2" "get from an empty queue"
./runtest.sh "tqueue 3" "put then get 3 elements"
./runtest.sh "tqueue 4" "put then get 100 elements"
./runtest.sh "tqueue 5" "apply a function to an empty queue"
./runtest.sh "tqueue 6" "apply a function to an nonempty queue"
./runtest.sh "tqueue 7" "search an empty queue"
./runtest.sh "tqueue 8" "remove from an empty queue"
./runtest.sh "tqueue 9" "concat 2 empty queues"
./runtest.sh "tqueue 10" "concat a nonempty to an empty queue"
./runtest.sh "tqueue 11" "concat an empty to a nonempty queue"
./runtest.sh "tqueue 12" "concat a nonempty to a nonempty queue"
./runtest.sh "tqueue 13" "search for the first element in a queue"
./runtest.sh "tqueue 14" "search for the last element in a queue"
./runtest.sh "tqueue 15" "search for an entry in the middle of a queue"
./runtest.sh "tqueue 16" "search for something thats not in the queue"
./runtest.sh "tqueue 17" "remove the first element of a queue"
./runtest.sh "tqueue 18" "remove the last element of a queue"
./runtest.sh "tqueue 19" "remove an element in the middle of a queue"
./runtest.sh "tqueue 20" "remove an element that is not present in a queue"
echo "[done]"

